on:
  push:
    branches:
      - '*'

name: Upload Binaries

jobs:
  release:
    name: Upload Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"

      - name: Build project
        run: go build -o secret-santa

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret-santa-${{ matrix.os }}
          path: ./secret-santa
